name: guard-result
on:
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  contents: read
jobs:
  guard:
    runs-on: ubuntu-latest
    env:
      THRESHOLD_PP: ${{ vars.THRESHOLD_PP }}
      FAIL_ON_DIFF: ${{ vars.FAIL_ON_DIFF }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: python -m pip install -U pip
      - run: python -m pip install -r requirements.txt
      - run: python -m pip install -r requirements-dev.txt || true
      - name: Build minimal diff (stub)
        run: |
          mkdir -p artifacts/summary
          printf "name,pp,delta_pp\nbase,0,0\n" > artifacts/summary/ab_diff.csv
      - run: bash scripts/guard.sh
