name: guard-result

on:
  workflow_run:
    workflows: ["pr-autocomment"]
    types:
      - completed

jobs:
  post_guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: python -m pip install -U pip
      - run: python -m pip install -r requirements.txt
      - run: python -m pip install -r requirements-dev.txt || true
      - run: bash scripts/guard.sh
