name: Guard RESULT

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - run: python -m pip install -U pip
      - run: python -m pip install -r requirements-dev.txt || true

      - name: Run integration tests (T400)
        run: make integration
        continue-on-error: ${{ vars.FAIL_ON_DIFF != '1' }}

      - name: Enforce strict mode if requested
        if: ${{ vars.FAIL_ON_DIFF == '1' && failure() }}
        run: exit 1
