name: Guard RESULT
on:
  pull_request_target:
permissions:
  contents: read
  pull-requests: write
jobs:
  guard:
    runs-on: ubuntu-latest
    env:
      THRESHOLD_PP: ${{ vars.THRESHOLD_PP || '2' }}
      FAIL_ON_DIFF: ${{ vars.FAIL_ON_DIFF || '0' }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup dev env
        run: |
          python3 -m pip install -U pip
          python3 -m pip install -r requirements-dev.txt
      - name: Run integration tests (T400)
        run: make integration
      - name: Sanity of artifacts
        run: |
          test -s artifacts/summary/ab_report.md
          ls -lh artifacts/summary || true
      - name: Post PR report comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: artifacts/summary/ab_report.md
          recreate: true
          header: "ab_report.md"
      - name: Fail on regression when strict
        if: ${{ env.FAIL_ON_DIFF == '1' }}
        run: |
          if [ -s artifacts/summary/ab_diff.csv ]; then
            echo Regression; exit 1;
          fi
