name: Guard RESULT

on:
  workflow_dispatch:
  push:
    branches:
      - chore/guard-hardening
      - main
      - master

jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build-min-artifacts
        run: |
          mkdir -p artifacts/summary
          printf "id,local,cloud\nT1,0,0\n" > artifacts/summary/ab_diff.csv
          echo x > artifacts/summary/passfail.png
      - name: run-guard
        run: |
          FAIL_ON_DIFF=1 bash scripts/guard_regress.sh
