name: nightly

on:
  workflow_dispatch:
  schedule:
    - cron: '17 05 * * *'
  pull_request:
    branches: [ master ]

permissions:
  contents: read
  actions: read
  pull-requests: write

jobs:
  t500:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install matplotlib pandas

      - name: Create venv
        run: python -m venv .venv

      - name: Run T500 benchmark
        run: |
          . .venv/bin/activate
          MODE=nightly LIMIT=500 bash scripts/ab_benchmark.sh "llama3.1:8b" "llama3.1:8b"

      - name: Write manifest
        run: |
          . .venv/bin/activate
          python scripts/write_manifest.py \
            --dataset tests/prompts.tsv --limit 500 \
            --mode nightly --model-a llama3.1:8b --model-b llama3.1:8b

      - name: Guard regress
        run: MODE=nightly FAIL_ON_DIFF=0 MIN_ROWS=500 bash scripts/guard_regress.sh

      - name: Pack nightly
        run: bash scripts/nightly_pack.sh

      - name: Retention (keep 14)
        run: KEEP_N=14 bash scripts/retention.sh artifacts/nightly 14

      - name: Upload nightly artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: nightly-${{ github.run_id }}
          if-no-files-found: error
          path: |
            artifacts/nightly/**/summary/*.csv
            artifacts/nightly/**/summary/*.tsv
            artifacts/nightly/**/summary/*.md
            artifacts/nightly/**/plots/*.png
            artifacts/nightly/**/manifest.json

      - name: Comment on PR with nightly results
        if: ${{ github.event_name == 'pull_request' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          MANIFEST=$(find artifacts/nightly -type f -name manifest.json | head -1 || true)
          if [ -n "$MANIFEST" ]; then
            BODY=$(bash scripts/ci_nightly_comment.sh "$MANIFEST")
            gh pr comment ${{ github.event.pull_request.number }} --body "$BODY"
          fi
