name: nightly_t1000

on:
  schedule:
    - cron: "27 2 * * *"
  workflow_dispatch:
    inputs:
      threshold:
        description: pass_rate threshold
        required: false
        default: "0.70"
      suite:
        description: suite
        required: false
        default: "t1000"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install matplotlib

      - run: bash scripts/start_t1000.sh ${{ inputs.suite || 't1000' }}
      - run: bash scripts/verify_t1000.sh ${{ inputs.suite || 't1000' }}
      - run: python3 scripts/metrics_rollup.py

      - id: parse
        run: |
          SUM=artifacts/t1000/latest/verify_summary.txt
          ROWS=$(awk -F'[=, ]+' '{for(i=1;i<=NF;i++) if($i=="rows"){print $(i+1); exit}}' "$SUM")
          PR=$(awk -F'[=, ]+' '{for(i=1;i<=NF;i++) if($i=="pass_rate"){print $(i+1); exit}}' "$SUM")
          DP=$(awk -F'[=, ]+' '{for(i=1;i<=NF;i++) if($i=="delta_pp"){print $(i+1); exit}}' "$SUM")
          echo "rows=$ROWS" >> $GITHUB_OUTPUT
          echo "pass_rate=$PR" >> $GITHUB_OUTPUT
          echo "delta_pp=$DP" >> $GITHUB_OUTPUT
          printf "rows=%s, pass_rate=%s, delta_pp=%s\n" "$ROWS" "$PR" "$DP"

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: t1000_artifacts
          path: |
            artifacts/t1000/latest
            artifacts/t1000/metrics_history.csv
            artifacts/t1000/passrate_local.png

      - name: Fail guard
        env:
          THRESHOLD: ${{ inputs.threshold || '0.70' }}
        run: |
          PR="${{ steps.parse.outputs.pass_rate }}"
          TH="$THRESHOLD"
          awk -v pr="$PR" -v th="$TH" 'BEGIN{ if ((pr+0) < (th+0)) exit 1 }'
