name: nightly

on:
  workflow_dispatch:
  schedule:
    - cron: '17 05 * * *'
  pull_request:
    branches: [ master ]

permissions:
  contents: read
  actions: read
  pull-requests: write

jobs:
  t500:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install matplotlib pandas

      - name: Run T500 benchmark
        run: |
          source .venv/bin/activate
          MODE=nightly LIMIT=500 bash scripts/ab_benchmark.sh "llama3.1:8b" "llama3.1:8b"

      - name: Write manifest
        run: |
          source .venv/bin/activate
          python scripts/write_manifest.py --dataset tests/prompts.tsv --limit 500 --mode nightly --model-a llama3.1:8b --model-b llama3.1:8b

      - name: Guard regress
        run: |
          source .venv/bin/activate
          MODE=nightly FAIL_ON_DIFF=0 MIN_ROWS=500 bash scripts/guard_regress.sh

      - name: Pack nightly
        run: bash scripts/nightly_pack.sh

      - name: Retention (keep 14)
        run: KEEP_N=14 bash scripts/retention.sh artifacts/nightly 14

      - name: Upload nightly artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: nightly-${{ github.run_id }}
          path: |
            artifacts/nightly/**/*
            artifacts/nightly/tmp/**/*

      - name: Comment on PR with nightly results
        if: ${{ github.event_name == 'pull_request' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          MANI=$(find artifacts/nightly/**/cloud_run_*/manifest.json 2>/dev/null | head -1 || true)
          if [ -z "$MANI" ]; then
            MANI=$(find artifacts/nightly/**/manifest.json 2>/dev/null | head -1 || true)
          fi
          if [ -n "$MANI" ]; then
            BODY=$(bash scripts/ci_nightly_comment.sh "$MANI")
          else
            MD=$(find artifacts/nightly/**/summary/*.md 2>/dev/null | head -1 || true)
            BODY="${MD:+Nightly summary attached.}"
          fi
          gh pr comment ${{ github.event.pull_request.number }} --body "$BODY"
