name: nightly_t3000
on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: python -m pip install -U pip
      - run: pip install -e .
      - run: bash scripts/run_t3000.sh tests/t3000.tsv artifacts/t3000 metrics_history.csv
      - uses: actions/upload-artifact@v4
        with:
          name: t3000_artifacts
          path: |
            artifacts/t3000/metrics.json
            artifacts/t3000/results.jsonl
