name: nightly_t1500

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prepare NLTK data
        run: |
          python - <<'PY'
          import nltk
          nltk.download('punkt', quiet=True)
          nltk.download('punkt_tab', quiet=True)
          PY

      - name: Run suite t1500
        run: bash scripts/run_t1500.sh
