name: nightly_t3000_rollup

on:
  schedule:
    - cron: "15 3 * * *"
  workflow_dispatch:

jobs:
  rollup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dawidd6/action-download-artifact@v3
        with:
          workflow: nightly_t3000.yml
          workflow_conclusion: success
          name: t3000_artifacts
          path: artifacts/t3000

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: python -m pip install -U pip
      - run: pip install -e .

      - run: bash scripts/run_t3000_rollup.sh artifacts/t3000 artifacts/metrics_history.csv artifacts/trend_drift_t3000.png

      - uses: actions/upload-artifact@v4
        with:
          name: t3000_rollup_artifacts
          path: artifacts
