name: nightly_t1000

on:
  schedule:
    - cron: "27 2 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install matplotlib
      - run: bash scripts/start_t1000.sh t1000
      - run: bash scripts/verify_t1000.sh t1000
      - run: python3 scripts/metrics_rollup.py

      - id: parse
        shell: bash
        run: |
          SUM=artifacts/t1000/latest/verify_summary.txt
          ROWS=$(grep -o 'rows=[0-9]\+' "$SUM" | cut -d= -f2)
          PR=$(grep -o 'pass_rate=[0-9.]\+' "$SUM" | cut -d= -f2)
          DP=$(grep -o 'delta_pp=[0-9.-]\+' "$SUM" | cut -d= -f2)
          echo "rows=${ROWS:-0}" >> "$GITHUB_OUTPUT"
          echo "pass_rate=${PR:-0}" >> "$GITHUB_OUTPUT"
          echo "delta_pp=${DP:-0}" >> "$GITHUB_OUTPUT"
          printf 'rows=%s, pass_rate=%s, delta_pp=%s\n' "${ROWS:-0}" "${PR:-0}" "${DP:-0}"

      - name: Fail guard
        env:
          THRESHOLD: "0.70"
          PR: ${{ steps.parse.outputs.pass_rate }}
        run: |
          awk -v pr="${PR:-0}" -v th="$THRESHOLD" 'BEGIN{ if ((pr+0) < (th+0)) exit 1 }'

      - uses: actions/upload-artifact@v4
        with:
          name: t1000_artifacts
          path: |
            artifacts/t1000/latest
            artifacts/t1000/metrics_history.csv
            artifacts/t1000/passrate_local.png
