ed -s .github/workflows/nightly_t1500_rollup.yml <<'ED'
g/^/,$d
$a
name: nightly_t1500_rollup

on:
  schedule:
    - cron: "10 3 * * *"
  workflow_dispatch:

jobs:
  rollup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download previous history
        uses: actions/download-artifact@v4
        with:
          name: metrics_history
          path: .
        continue-on-error: true

      - name: Ensure history exists
        run: |
          test -f metrics_history.csv || echo "timestamp,run,suite,passrate,fails,notes" > metrics_history.csv

      - name: Rollup
        run: bash scripts/run_rollup.sh

      - name: Upload history
        uses: actions/upload-artifact@v4
        with:
          name: metrics_history
          path: metrics_history.csv
          if-no-files-found: warn
.
wq
ED
