name: PR Report Comment

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install deps
        run: python3 -m pip install -U pip

      - name: Set env
        run: echo "OK"
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Run mini bench
        run: |
          bash scripts/run_ab.sh llama3.1:8b gpt-4o-mini
          test -f artifacts/summary/ab_report.md

      - name: Prepare PR body
        run: |
          printf "<!-- ab_report -->\n" > /tmp/pr_body.md
          cat artifacts/summary/ab_report.md >> /tmp/pr_body.md

      - name: Find existing comment
        id: find
        uses: peter-evans/find-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: github-actions[bot]
          body-includes: "<!-- ab_report -->"

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.find.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body-file: /tmp/pr_body.md
          edit-mode: replace
