name: PR Report Comment

on:
  pull_request:

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install -U pip matplotlib

      - name: Run mini bench
        run: |
          bash scripts/run_ab.sh llama3.1:8b gpt-4o-mini
          python3 scripts/run_ab.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pr-report
          path: |
            artifacts/summary/*
            artifacts/plots/*
            artifacts/manifest.json
