name: PR Report Comment
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          echo "PY=$pythonLocation/bin/python" >> $GITHUB_ENV
          echo "Using Python: $PY"
          $pythonLocation/bin/python -m pip install -U pip
          $pythonLocation/bin/python -m pip install matplotlib
      - name: Run mini bench
        run: |
          bash scripts/run_ab.sh llama3.1:8b gpt-4o-mini
