name: PR Report Comment
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python  -m pip install -U pip matplotlib
          python3 -m pip install -U pip matplotlib

      - name: Run mini bench
        run: |
          bash scripts/run_ab.sh llama3.1:8b gpt-4o-mini
