name: pre-ci
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  checks: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install deps
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          if [ -f pyproject.toml ]; then pip install -e . || true; fi
          pip install pytest

      - name: Lint and hooks
        run: |
          pip install pre-commit
          pre-commit run --all-files

      - name: Tests
        run: pytest -q

      - name: Build report (skip if no Makefile:report)
        run: |
          if [ -f Makefile ] && grep -qE '^[[:space:]]*report:' Makefile; then
            make report
          else
            echo "no Makefile:report — skipping"
            mkdir -p artifacts/summary
          fi

      - name: Upload preci-report
        uses: actions/upload-artifact@v4
        with:
          name: preci-report
          path: artifacts/summary
          if-no-files-found: ignore
          retention-days: 7
