name: Pre-CI

on:
  push:
  pull_request:

jobs:
  precheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Validate test_prompts.json
        run: |
          python -m json.tool test_prompts.json > /dev/null

      - name: Check Python scripts are runnable
        run: |
          for f in scripts/*.py; do
            echo "Checking $f"
            python3 "$f" --help || true
          done

      - name: Build report from existing artifacts
        run: |
          python3 scripts/build_report.py --artifacts artifacts --output artifacts/summary/preci_report.md
