name: pre-ci
on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  checks: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
      - name: Lint and hooks
        run: |
          pip install pre-commit
          pre-commit run --all-files
      - name: Tests
        run: pytest -q
      - name: Build report
        run: make report
      - name: Upload preci-report
        uses: actions/upload-artifact@v4
        with:
          name: preci-report
          path: artifacts/summary
          if-no-files-found: ignore
          retention-days: 7
