name: Pre-CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest requests pandas

      - name: Run tests
        run: pytest -q

      # Готовим папку с отчетами; если файлы не созданы тестами — создаём заглушки,
      # чтобы upload-artifact всегда находил, что упаковать.
      - name: Prepare artifact folder (preci-report)
        run: |
          mkdir -p artifacts/summary
          [[ -f artifacts/summary/judgement.tsv ]] || printf "test\tverdict\n" > artifacts/summary/judgement.tsv
          [[ -f artifacts/summary/stability.tsv ]] || printf "metric\tvalue\n" > artifacts/summary/stability.tsv

      # Публикуем артефакт, который guard_regress подтянет в следующих прогонах
      - name: Upload regression artifacts
        uses: actions/upload-artifact@v4
        with:
          name: preci-report
          path: artifacts/summary/
          if-no-files-found: warn
          retention-days: 7

      - name: Make guard script executable
        run: chmod +x scripts/guard_regress.sh

      - name: Run regression guard
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: ./scripts/guard_regress.sh
