name: pre-ci

on:
  pull_request:
    types: [synchronize, opened, reopened]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  pre-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -U pip
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-dev.txt || true

      - name: Diagnostics
        run: |
          python --version
          pip --version
          ls -lah

      # Быстрый прогон T1–T26. Тут НЕТ генерации артефактов и НЕТ guard.sh
      - name: Run integration (T1–T26)
        run: |
          make integration || pytest -q tests/integration
