name: nightly_t1500_rollup
on:
  workflow_dispatch:
  schedule:
    - cron: "15 2 * * *"
permissions:
  contents: read
concurrency:
  group: nightly_t1500_rollup
  cancel-in-progress: false
jobs:
  rollup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install matplotlib
      - name: Rollup
        env:
          PYTHONPATH: .
        run: |
          bash scripts/run_rollup.sh
      - name: Upload plots
        uses: actions/upload-artifact@v4
        with:
          name: t1500-trends
          path: |
            artifacts/passtrate_trend.png
            artifacts/trend_bleu.png
            artifacts/trend_rouge.png
            artifacts/semantic_drift.png
          if-no-files-found: ignore
          retention-days: 30
