name: t2000_drift
on:
  workflow_dispatch:
  push:
    paths:
      - "tests/t2000.tsv"
      - "sigma/**"
      - "scripts/**"
jobs:
  drift:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: python -m pip install -U pip
      - run: pip install -e .
      - run: bash scripts/run_t2000.sh tests/t2000.tsv artifacts/t2000 artifacts/metrics_history.csv
      - run: python3 scripts/drift_t2000.py artifacts/metrics_history.csv artifacts/stability_t2000.tsv
      - uses: actions/upload-artifact@v4
        with:
          name: t2000_drift
          path: artifacts
